Repository domludera/SOEN341UA4, pull requests merged in 2019-04, with the labels that each got.

#56 Update README.md
  README.md
Labels: invalid

#57 fixed navbar and titles
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/style.css
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/template.html
  twitter_clone/twitter_clone_app/views.py
Labels: bug, enhancement, frontend

#58 Merge Meta+Test into Master
  twitter_clone/twitter_clone_app/static/twitter_clone_app/images/chirp.gif
  twitter_clone/twitter_clone_app/static/twitter_clone_app/images/flavicon.png
  twitter_clone/twitter_clone_app/templates/registration/login.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/home.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/profile.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/template.html
  twitter_clone/twitter_clone_app/views.py
Labels: Priority: medium

#59 Auto formating of the project
  twitter_clone/twitter_clone_app/views.py
Labels: Priority: low

#60 fixed font color and margins
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/style.css
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/registration.html
Labels: bug, enhancement, frontend
