Repository domludera/SOEN341UA4, pull requests merged in 2019-03, with the labels that each got.

#33 merge likingTweets inside master
  twitter_clone/twitter_clone_app/migrations/0002_chirp_likes.py
  twitter_clone/twitter_clone_app/models.py
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/home.html
  twitter_clone/twitter_clone_app/views.py
Labels: Priority: high, SP: 1, Sprint3

#44 Unit test integration
  .travis.yml
  requirements.txt
  twitter_clone/__init__.py
  twitter_clone/twitter_clone/settings.py
  twitter_clone/twitter_clone_app/__init__.py
  twitter_clone/twitter_clone_app/tests.py
Labels: Priority: high, SP: 3, Sprint3, backend, risk: medium, test

#46 Merge UnitTestMainFeatures into master
  .travis.yml
  requirements.txt
  twitter_clone/twitter_clone/settings.py
  twitter_clone/twitter_clone_app/tests.py
  twitter_clone/twitter_clone_app/tests/__init__.py
  twitter_clone/twitter_clone_app/tests/test_core_features.py
Labels: Priority: high, SP: 5, backend, test

#49 Merge codeCov into master
  .travis.yml
  README.md
  twitter_clone/twitter_clone/settings.py
Labels: Priority: high, SP: 1, Sprint 4, backend

#50 CSS and UI
  .gitignore
  twitter_clone/twitter_clone_app/forms.py
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/home.css
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/login.css
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/profile.css
  twitter_clone/twitter_clone_app/static/twitter_clone_app/css/style.css
  twitter_clone/twitter_clone_app/static/twitter_clone_app/images/7160.jpg
  twitter_clone/twitter_clone_app/templates/registration/login.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/home.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/my-profile.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/template.html
Labels: Priority: high, SP: 4, Sprint 4, enhancement, frontend, risk: low

#51 merge userProfiles into master
  twitter_clone/twitter_clone/settings.py
  twitter_clone/twitter_clone/urls.py
  twitter_clone/twitter_clone_app/templates/registration/login.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/home.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/my-profile.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/profile.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/template.html
  twitter_clone/twitter_clone_app/templates/twitter_clone_app/users-profiles.html
  twitter_clone/twitter_clone_app/tests/test_core_features.py
  twitter_clone/twitter_clone_app/urls.py
  twitter_clone/twitter_clone_app/views.py
Labels: Priority: high, SP: 3, Sprint 4

#54 Added extra feature pull request
  twitter_clone/twitter_clone_app/tests/test_core_features.py
Labels: Priority: high, SP: 2, Sprint 4
